### ISSUE TITLE
Add caching to API calls

### ISSUE THREAD

**Issue by bartlannoeye** [AppCreativity/Kliva#31]
Strava api calls are limited in time
- In memory vs on disk (eg Akavache)
- Different timespans as some endpoints expire faster (eg kudos/comments)

**Comment by Depechie** [comment]
I've already added some in memory caches through use of a ConcurrentDictionary<key, T> where T is a Task<T>. That way when multiple requests are made of the same data, it will only go 'online' once for  the first request.
These caches are not yet time based, so not invalidated during the use of the app. But for the information we are using this, it's not yet that critical ( Photo and Athlete ).

We still need to see how we also cache results on disk and add timestamps.

**Comment by samsp** [comment]
Some of this is fixed with CKILB for the activity list.

I extended the AthleteService to hold a cache of the actual athlete objects, or tasks to fetch them. So calling GetAthleteAsync(athleteID) will give back either a cached value, or a task to fetch it.
The consolidateWithCache method will take an athleteMeta|athleteSummary|athlete and determine whether the cache or the one passed in has more data and is more recent (due to timestamp from the service) and return the most appropriate.
