### ISSUE TITLE
Can not Login

### ISSUE THREAD

**Issue by michaelcoelsch** [AppCreativity/Kliva#92]
Hi,
i can not login to Kliva on a German Windows 10.

After tapping the Login-Button, i get an error message in an empty window saying that "the service can not be connected, please try later"

What can i do?
Thanks
![klivalogin](https://cloud.githubusercontent.com/assets/6121332/19144081/eed1e94e-8ba7-11e6-994f-508ffc02ebec.PNG)

**Comment by Depechie** [comment]
Hey @michaelcoelsch first up thanks for trying out our app!
But what you should know, is that we have not added our API keys to this Open Source Project, you can see this because the file https://github.com/AppCreativity/Kliva/blob/master/src/Kliva/Models/StravaIdentityConstants.cs has 'dummy' data.

If you actually would like to run the app ( other than just looking at the code ), I can mail you these settings IF you promise not to dump them any where online ;)
The API calls to Strava are per app limited, so if any other apps would use our key, we would hit that limit fast :(

**Comment by michaelcoelsch** [comment]
Thanks for quick reply!
Of course i will keep the account in my office only.

**Comment by Depechie** [comment]
Ok I'll mail them as soon as I reach my dev machine at home this evening, and seeing you have experience in app dev ( looking at your website ), we are always open for contributions to this project ;)

**Comment by michaelcoelsch** [comment]
Thanks :-)

**Comment by shridhar083** [comment]
hi, same here can not login to Kliva ... at least when click on login if any dummy data is fetched, it helps a lot....

**Comment by bartlannoeye** [comment]
We're looking into this with Strava for a permanent solution. It's not our intention to share the API key with the whole internet. For now, you can request your own API key on strava.com

**Comment by bartlannoeye** [comment]
We provided debug keys in the solution to test the app. For anything other than just trying out the app, please request your own api keys on strava.com
